import 'dart:io';
import 'dart:isolate';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:image/image.dart' as img;
import 'package:onnxruntime/onnxruntime.dart';

import 'segmentation_engine.dart';

/// Background removal using a u2netp ONNX model bundled inside the app.
///
/// This is the engine that makes the feature work everywhere: no Play
/// Services, no first-run model download, no Google dependency, and it is the
/// only option on iOS (the ML Kit plugin's iOS half is a stub). It costs
/// 4.4 MB of APK size.
///
/// Quality note, measured rather than assumed: with the guided-filter
/// refinement applied afterwards this reaches IoU 0.958 against a 170 MB
/// model, which is fine for solid products. On a *bare thin chain* it keeps
/// only ~69% of the pixels, so jewellery photographed with a lot of exposed
/// chain is the case where it is visibly weaker.
///
/// Every constant below mirrors the reference implementation this was
/// validated against. They are not free parameters -- changing one silently
/// produces a wrong mask rather than an error.
class U2netpSegmentationEngine implements SegmentationEngine {
  static const String assetPath = 'assets/models/u2netp.onnx';

  /// The model's input is a fixed [1, 3, 320, 320] tensor.
  static const int _edge = 320;

  /// ImageNet channel statistics, as used by u2netp.
  static const List<double> _mean = [0.485, 0.456, 0.406];
  static const List<double> _std = [0.229, 0.224, 0.225];

  OrtSession? _session;

  Future<OrtSession> _ensureSession() async {
    final existing = _session;
    if (existing != null) return existing;

    OrtEnv.instance.init();
    final raw = await rootBundle.load(assetPath);
    final session = OrtSession.fromBuffer(
      raw.buffer.asUint8List(raw.offsetInBytes, raw.lengthInBytes),
      OrtSessionOptions(),
    );
    _session = session;
    return session;
  }

  @override
  Future<SegmentationResult> segment(String imagePath, int width, int height) async {
    final session = await _ensureSession();

    final bytes = await File(imagePath).readAsBytes();

    // Decode + resize + normalise is pure CPU work on a few megabytes, so it
    // goes to a background isolate to keep the UI responsive.
    final input = await Isolate.run(() => _preprocess(bytes));

    final inputTensor = OrtValueTensor.createTensorWithDataList(
      input,
      [1, 3, _edge, _edge],
    );
    final runOptions = OrtRunOptions();

    List<OrtValue?>? outputs;
    try {
      // Names are read from the model rather than hard-coded: u2netp's are
      // autogenerated ('input.1', '1959'), which is exactly the kind of
      // string that silently breaks if the asset is ever regenerated.
      outputs = await session.runAsync(
        runOptions,
        {session.inputNames.first: inputTensor},
      );

      if (outputs == null || outputs.isEmpty) {
        throw const SegmentationUnavailable(
          'The bundled model returned no output.',
        );
      }

      // u2netp emits seven side outputs (one per decoder stage). The first is
      // the fused, full-quality mask; the rest are coarser supervision
      // outputs used during training.
      final raw = outputs.first?.value;
      final mask = _extractMask(raw);

      return SegmentationResult(
        alpha: _toFullSize(mask, width, height),
        width: width,
        height: height,
      );
    } finally {
      inputTensor.release();
      runOptions.release();
      outputs?.forEach((o) => o?.release());
    }
  }

  /// Builds the [1,3,320,320] input tensor.
  ///
  /// Deliberately mirrors the reference pipeline, including the unusual
  /// scaling step: pixels are divided by the image's own **maximum value**,
  /// not by 255. That is what u2netp's published preprocessing does, and a
  /// plain /255 shifts the input distribution enough to degrade the mask.
  static Float32List _preprocess(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw const FormatException('Could not decode the working image.');
    }

    // Cubic, not average/linear: measured against the reference LANCZOS
    // resize, cubic agreed most closely (IoU 0.96-0.99 on real photos, vs
    // 0.93-0.98 for the alternatives).
    final resized = img.copyResize(
      decoded,
      width: _edge,
      height: _edge,
      interpolation: img.Interpolation.cubic,
    );

    final plane = _edge * _edge;
    final rgb = Uint8List(plane * 3);
    var maxValue = 0;
    var i = 0;
    for (var y = 0; y < _edge; y++) {
      for (var x = 0; x < _edge; x++) {
        final p = resized.getPixel(x, y);
        final r = p.r.toInt(), g = p.g.toInt(), b = p.b.toInt();
        rgb[i] = r;
        rgb[i + plane] = g;
        rgb[i + plane * 2] = b;
        if (r > maxValue) maxValue = r;
        if (g > maxValue) maxValue = g;
        if (b > maxValue) maxValue = b;
        i++;
      }
    }

    final scale = 1.0 / math.max(maxValue.toDouble(), 1e-6);
    final out = Float32List(plane * 3);
    for (var c = 0; c < 3; c++) {
      final offset = c * plane;
      final mean = _mean[c];
      final std = _std[c];
      for (var j = 0; j < plane; j++) {
        out[offset + j] = ((rgb[offset + j] * scale) - mean) / std;
      }
    }
    return out;
  }

  /// Pulls the [1,1,320,320] output into a flat, min-max normalised mask.
  ///
  /// The raw network output is unbounded logits, so the reference
  /// implementation rescales by the observed min/max before use.
  static Float32List _extractMask(Object? raw) {
    if (raw is! List) {
      throw const SegmentationUnavailable(
        'The bundled model returned an unexpected output type.',
      );
    }

    // Shape is [1,1,320,320]; the package hands it back as nested lists.
    final plane = (raw[0] as List)[0] as List;
    final flat = Float32List(_edge * _edge);
    var min = double.infinity;
    var max = double.negativeInfinity;

    var i = 0;
    for (var y = 0; y < _edge; y++) {
      final row = plane[y] as List;
      for (var x = 0; x < _edge; x++) {
        final v = (row[x] as num).toDouble();
        flat[i++] = v;
        if (v < min) min = v;
        if (v > max) max = v;
      }
    }

    final range = max - min;
    if (range <= 1e-12) {
      // Uniform output means the model found nothing to separate.
      return Float32List(_edge * _edge);
    }
    for (var j = 0; j < flat.length; j++) {
      flat[j] = ((flat[j] - min) / range).clamp(0.0, 1.0);
    }
    return flat;
  }

  /// Scales the 320x320 mask up to the working image's size.
  static Float32List _toFullSize(Float32List mask, int width, int height) {
    final small = img.Image(width: _edge, height: _edge, numChannels: 1);
    for (var y = 0; y < _edge; y++) {
      for (var x = 0; x < _edge; x++) {
        final v = (mask[y * _edge + x] * 255).round().clamp(0, 255);
        small.setPixelRgba(x, y, v, v, v, 255);
      }
    }

    final big = img.copyResize(
      small,
      width: width,
      height: height,
      interpolation: img.Interpolation.cubic,
    );

    final alpha = Float32List(width * height);
    var i = 0;
    for (var y = 0; y < height; y++) {
      for (var x = 0; x < width; x++) {
        alpha[i++] = big.getPixel(x, y).r / 255.0;
      }
    }
    return alpha;
  }

  @override
  Future<void> dispose() async {
    _session?.release();
    _session = null;
  }
}
