import 'dart:io';
import 'dart:isolate';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_onnxruntime/flutter_onnxruntime.dart';
import 'package:image/image.dart' as img;

import 'segmentation_engine.dart';

/// Background removal using a u2netp ONNX model bundled inside the app.
///
/// This is the engine that makes the feature work everywhere: no Play
/// Services, no first-run model download, no Google dependency, and it is the
/// only option on iOS (the ML Kit plugin's iOS half is a stub). It costs
/// 4.4 MB of APK size.
///
/// Quality note, measured rather than assumed: with the guided-filter
/// refinement applied afterwards this reaches IoU 0.958 against a 170 MB
/// model, which is fine for solid products. On a *bare thin chain* it keeps
/// only ~69% of the pixels, so jewellery photographed with a lot of exposed
/// chain is the case where it is visibly weaker.
///
/// Every constant below mirrors the reference implementation this was
/// validated against. They are not free parameters -- changing one silently
/// produces a wrong mask rather than an error.
class U2netpSegmentationEngine implements SegmentationEngine {
  static const String assetPath = 'assets/models/u2netp.onnx';

  /// The model's input is a fixed [1, 3, 320, 320] tensor.
  static const int _edge = 320;

  /// ImageNet channel statistics, as used by u2netp.
  static const List<double> _mean = [0.485, 0.456, 0.406];
  static const List<double> _std = [0.229, 0.224, 0.225];

  final OnnxRuntime _runtime = OnnxRuntime();
  OrtSession? _session;

  Future<OrtSession> _ensureSession() async {
    final existing = _session;
    if (existing != null) return existing;
    // Handles extracting the asset to a real file, caching it between runs,
    // and re-extracting if a cached copy turns out to be corrupt.
    final session = await _runtime.createSessionFromAsset(assetPath);
    _session = session;
    return session;
  }

  @override
  Future<SegmentationResult> segment(String imagePath, int width, int height) async {
    final session = await _ensureSession();
    final bytes = await File(imagePath).readAsBytes();

    // Decode + resize + normalise is pure CPU work on a few megabytes, so it
    // goes to a background isolate to keep the UI responsive.
    final input = await Isolate.run(() => _preprocess(bytes));

    final inputTensor = await OrtValue.fromList(input, [1, 3, _edge, _edge]);
    Map<String, OrtValue>? outputs;
    try {
      // Names come from the model rather than being hard-coded: u2netp's are
      // autogenerated ('input.1', '1959'), exactly the kind of string that
      // breaks silently if the asset is ever regenerated.
      outputs = await session.run({session.inputNames.first: inputTensor});

      // u2netp emits seven side outputs (one per decoder stage). The first is
      // the fused, full-quality mask; the rest are coarser supervision
      // outputs used during training.
      final out = outputs[session.outputNames.first];
      if (out == null) {
        throw const SegmentationUnavailable(
          'The bundled model returned no output.',
        );
      }

      final flat = await out.asFlattenedList();
      return SegmentationResult(
        alpha: _toFullSize(_normalise(flat), width, height),
        width: width,
        height: height,
      );
    } finally {
      await inputTensor.dispose();
      if (outputs != null) {
        for (final v in outputs.values) {
          await v.dispose();
        }
      }
    }
  }

  /// Builds the [1,3,320,320] input tensor.
  ///
  /// Deliberately mirrors the reference pipeline, including the unusual
  /// scaling step: pixels are divided by the image's own **maximum value**,
  /// not by 255. That is what u2netp's published preprocessing does, and a
  /// plain /255 shifts the input distribution enough to degrade the mask.
  static Float32List _preprocess(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw const FormatException('Could not decode the working image.');
    }

    // Cubic, not average/linear: measured against the reference LANCZOS
    // resize, cubic agreed most closely (IoU 0.96-0.99 on real photos, vs
    // 0.93-0.98 for the alternatives).
    final resized = img.copyResize(
      decoded,
      width: _edge,
      height: _edge,
      interpolation: img.Interpolation.cubic,
    );

    final plane = _edge * _edge;
    final rgb = Uint8List(plane * 3);
    var maxValue = 0;
    var i = 0;
    for (var y = 0; y < _edge; y++) {
      for (var x = 0; x < _edge; x++) {
        final p = resized.getPixel(x, y);
        final r = p.r.toInt(), g = p.g.toInt(), b = p.b.toInt();
        rgb[i] = r;
        rgb[i + plane] = g;
        rgb[i + plane * 2] = b;
        if (r > maxValue) maxValue = r;
        if (g > maxValue) maxValue = g;
        if (b > maxValue) maxValue = b;
        i++;
      }
    }

    final scale = 1.0 / math.max(maxValue.toDouble(), 1e-6);
    final out = Float32List(plane * 3);
    for (var c = 0; c < 3; c++) {
      final offset = c * plane;
      final mean = _mean[c];
      final std = _std[c];
      for (var j = 0; j < plane; j++) {
        out[offset + j] = ((rgb[offset + j] * scale) - mean) / std;
      }
    }
    return out;
  }

  /// Min-max rescales the raw output.
  ///
  /// The network emits unbounded values, so the reference implementation
  /// normalises by the observed min/max before treating them as an alpha.
  static Float32List _normalise(List<dynamic> raw) {
    final n = _edge * _edge;
    if (raw.length < n) {
      throw SegmentationUnavailable(
        'The bundled model returned ${raw.length} values, expected $n.',
      );
    }

    final flat = Float32List(n);
    var min = double.infinity;
    var max = double.negativeInfinity;
    for (var i = 0; i < n; i++) {
      final v = (raw[i] as num).toDouble();
      flat[i] = v;
      if (v < min) min = v;
      if (v > max) max = v;
    }

    final range = max - min;
    if (range <= 1e-12) {
      // Uniform output means the model found nothing to separate.
      return Float32List(n);
    }
    for (var i = 0; i < n; i++) {
      flat[i] = ((flat[i] - min) / range).clamp(0.0, 1.0);
    }
    return flat;
  }

  /// Scales the 320x320 mask up to the working image's size.
  static Float32List _toFullSize(Float32List mask, int width, int height) {
    final small = img.Image(width: _edge, height: _edge, numChannels: 1);
    for (var y = 0; y < _edge; y++) {
      for (var x = 0; x < _edge; x++) {
        final v = (mask[y * _edge + x] * 255).round().clamp(0, 255);
        small.setPixelRgba(x, y, v, v, v, 255);
      }
    }

    final big = img.copyResize(
      small,
      width: width,
      height: height,
      interpolation: img.Interpolation.cubic,
    );

    final alpha = Float32List(width * height);
    var i = 0;
    for (var y = 0; y < height; y++) {
      for (var x = 0; x < width; x++) {
        alpha[i++] = big.getPixel(x, y).r / 255.0;
      }
    }
    return alpha;
  }

  @override
  Future<void> dispose() async {
    await _session?.close();
    _session = null;
  }
}
